import type { Agente, Cliente, Ciudad, Evento, Reserva, Usuario } from '../models';

export const ciudades: Ciudad[] = [
  { id: 'bogota', nombre: 'Bogotá', departamento: 'Cundinamarca', pais: 'Colombia' },
  { id: 'medellin', nombre: 'Medellín', departamento: 'Antioquia', pais: 'Colombia' },
  { id: 'cali', nombre: 'Cali', departamento: 'Valle del Cauca', pais: 'Colombia' },
  { id: 'barranquilla', nombre: 'Barranquilla', departamento: 'Atlántico', pais: 'Colombia' },
  { id: 'pereira', nombre: 'Pereira', departamento: 'Risaralda', pais: 'Colombia' },
];

export const usuarios: Usuario[] = [
  {
    id: 'cliente-1',
    tipo: 'cliente',
    identificacion: '1001234567',
    nombreCompleto: 'Ana García',
    email: 'ana@correo.com',
    password: '123456',
    direccion: 'Calle 45 #12-30',
    ciudadId: 'bogota',
    telefonos: ['3001112233'],
  },
  {
    id: 'cliente-2',
    tipo: 'cliente',
    identificacion: '1007654321',
    nombreCompleto: 'Luis Torres',
    email: 'luis@correo.com',
    password: '123456',
    direccion: 'Carrera 15 #98-10',
    ciudadId: 'medellin',
    telefonos: ['3109876543'],
  },
  {
    id: 'agente-1',
    tipo: 'agente',
    identificacion: '2001234567',
    nombreCompleto: 'María López',
    email: 'maria@agente.com',
    password: '123456',
    direccion: 'Avenida 7 #21-15',
    ciudadId: 'cali',
    telefonos: ['3017766554'],
  },
  {
    id: 'admin-1',
    tipo: 'admin',
    identificacion: '3001234567',
    nombreCompleto: 'Carlos Ramírez',
    email: 'admin@eventosapp.com',
    password: '123456',
    direccion: 'Diagonal 28 #34-45',
    ciudadId: 'bogota',
    telefonos: ['3201234567'],
  },
];

export const clientes: Cliente[] = [
  {
    ...usuarios[0],
    tipo: 'cliente',
    puntos: 1500,
    publicidad: true,
  },
  {
    ...usuarios[1],
    tipo: 'cliente',
    puntos: 980,
    publicidad: false,
  },
];

export const agentes: Agente[] = [
  {
    ...usuarios[2],
    tipo: 'agente',
    comision: 12.5,
    experiencia: '3 años en ventas de eventos y boletería',
  },
];

export const eventos: Evento[] = [
  {
    id: 'ev-1',
    codigo: 'EV-1001',
    nombre: 'Concierto de Rock en Vivo',
    descripcion: 'Noche de música en vivo con artistas locales e internacionales.',
    teatro: 'Teatro Colón',
    ciudadId: 'bogota',
    fechaInicio: '2026-10-15T19:30',
    fechaFin: '2026-10-15T22:30',
    capacidad: 450,
    precioBase: 120000,
    observaciones: 'Se recomienda llegar 45 minutos antes.',
    estado: 'Programado',
    agenteId: 'agente-1',
  },
  {
    id: 'ev-2',
    codigo: 'EV-1002',
    nombre: 'Festival de Jazz',
    descripcion: 'Festival con grupos de jazz, improvisación y música experimental.',
    teatro: 'Auditorio Plaza',
    ciudadId: 'medellin',
    fechaInicio: '2026-11-02T18:00',
    fechaFin: '2026-11-02T23:00',
    capacidad: 300,
    precioBase: 95000,
    observaciones: 'Venta anticipada disponible.',
    estado: 'En Boletería',
    agenteId: 'agente-1',
  },
  {
    id: 'ev-3',
    codigo: 'EV-1003',
    nombre: 'Teatro Musical: El Viaje',
    descripcion: 'Producción teatral con música en vivo y narrativa escénica.',
    teatro: 'Centro Cultural Cali',
    ciudadId: 'cali',
    fechaInicio: '2026-09-28T20:00',
    fechaFin: '2026-09-28T22:15',
    capacidad: 220,
    precioBase: 80000,
    observaciones: 'Se habilita sector VIP.',
    estado: 'En Vivo',
    agenteId: 'agente-1',
  },
  {
    id: 'ev-4',
    codigo: 'EV-1004',
    nombre: 'Expo Emprendimiento',
    descripcion: 'Encuentro de empresas, startups y networking para emprendedores.',
    teatro: 'Campo Verde',
    ciudadId: 'barranquilla',
    fechaInicio: '2026-12-05T09:00',
    fechaFin: '2026-12-05T17:00',
    capacidad: 500,
    precioBase: 60000,
    observaciones: 'Ingreso libre para estudiantes.',
    estado: 'Programado',
    agenteId: 'agente-1',
  },
];

export const reservas: Reserva[] = [
  {
    id: 'res-1',
    clienteId: 'cliente-1',
    eventoId: 'ev-1',
    fechaReserva: '2026-09-10T14:00',
    numeroEntradas: 2,
    valorTotal: 240000,
    observaciones: 'Preferencia fila central.',
    estado: 'Confirmada',
  },
  {
    id: 'res-2',
    clienteId: 'cliente-1',
    eventoId: 'ev-2',
    fechaReserva: '2026-09-12T09:35',
    numeroEntradas: 1,
    valorTotal: 95000,
    observaciones: 'Reserva estándar.',
    estado: 'Reservada',
  },
  {
    id: 'res-3',
    clienteId: 'cliente-2',
    eventoId: 'ev-3',
    fechaReserva: '2026-09-14T10:10',
    numeroEntradas: 3,
    valorTotal: 240000,
    observaciones: 'Necesitan asiento juntos.',
    estado: 'Cancelada',
  },
  {
    id: 'res-4',
    clienteId: 'cliente-2',
    eventoId: 'ev-4',
    fechaReserva: '2026-09-18T18:20',
    numeroEntradas: 2,
    valorTotal: 120000,
    observaciones: 'Confirmación por WhatsApp.',
    estado: 'Reservada',
  },
];
